# This is a basic workflow to help you get started with Actions

name: build_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command to install node
      - name: Installing Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      # Runs a command to install firebase tools
      - name: Installing Firebase
        run: npm install -g firebase-tools
        
      # Runs a command to deploy to firebase
      - name: Firebase Deployment
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
